accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup')
]

chat/urls.py
from django.urls import path
from chat import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room')
]

messagingapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home')
]

accounts/models.py
from django.db import models

# Create your models here.

chat/models.py
from django.db import models

# Create your models here.


#class User(models.Model):


#class ChatRoom(models.Model):

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

# accounts views.py

class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

chat/views.py
from django.shortcuts import render
from django.utils.safestring import mark_safe
import json

# chat views.py

def index(request):
    return render(request, 'chat/index.html', {})

def room(request, room_name):
    return render(request, 'chat/room.html', {
        'room_name_json': mark_safe(json.dumps(room_name))
    })

chat/templates/chat/index.html
{% extends 'base.html' %}

{% block title %}Chat List{% endblock %}

{% block content %}
    <h1>Welcome to the chat room list, {{user.username}}.</h1>
    <h2>Pick a room to join:</h2>
    {% comment %} 
    {% for room in room_list %}
    <div>
        <span>{{room.name}}</span>
        <span> | Users: {{ room.users.count }} </span>
        <a href="{% url room.name %}">Enter</a>
    </div>
    {% endfor %} 
    {% endcomment %}

   <h2>Or make a new room:</h2>
    {% comment %} <form method="post">
        {% csrf_token %}
        <input type="text" name="room-name" placeholder="Enter room name.."><br/>
        <input type="submit" value="Create Room">
    </form> {% endcomment %}
{% endblock %}

{% block scripts %}
<script type="text/javascript">


</script>
{% endblock %}

chat/templates/chat/room.html
{% extends 'base.html' %}

{% block title %}Chat Room{% endblock %}

{% block content %}
    <h1 id="room-name"></h1>
    <textarea id="chat-log" cols="100" rows="20" style="resize: none;"></textarea><br/>
    <input id="message-input" type="text" size="100" placeholder="Enter message here..."><br/>
    <input id="message-submit" type="button" value="Send">
{% endblock %}

{% block scripts %}
<script type='text/javascript'>

    // document nodes used in script
    const chatLog = document.querySelector('#chat-log');
    const roomNameNode = document.querySelector('#room-name');

    var roomNameValue = {{ room_name_json }};

    changeNodeText(roomNameNode, roomNameValue);

    // helper function
    function changeNodeText(node, text) {
        node.innerText = text.trim();
    } 

    // websocket
    var chatSocket = new WebSocket(
        'ws://' + window.location.host + 
        '/ws/chat/' + roomNameValue + '/'
    );

    // websocket listeners
    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var message = data['message'];
        chatLog.value += (message + '\n');
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    // events listeners for message-input and message-submit
    document.querySelector('#message-input').focus();
    document.querySelector('#message-input').onkeyup = function(e) {
        // check if enter key is enter/return
        if (e.keycode === 13) {
            document.querySelector('#message-submit').click();
        }
    }
    document.querySelector('#message-submit').onclick = function(e) {
        var messageInput = document.querySelector('#message-input');
        var message = messageInput.value;
        chatSocket.send(JSON.stringify({
            'message': message
        }));

        messageInput.value = '';
    }
</script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}App{% endblock %}</title>
    </head>
    <body>
        <main>
            {% block content %}
            <p>
                <a href="{% url 'logout' %}">Logout</a>
            </p>
            {% endblock %}
        </main>
    </body>
    {% block scripts %}
    {% endblock %}
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
    <h2>Hi {{user.username}}<h2>
    <p>
        <a href="{% url 'chat:index' %}">Go to chat room list</a>
    </p>
{% else %}
    <p>You are not logged in.</p>
    <a href="{% url 'login' %}">Login</a>
{% endif %}
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<h2>Sign up</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Sign Up</button>
</form>
{% endblock %}